language: node_js
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "ap-south-1"  
  app: "Sampleapp"
  env: "Sampleapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-573034299960"
  on:
branch: master